name: CI Pipeline

on:
  push:
    branches:
      - main  # 只在 main 分支发生 push 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境执行任务

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install  # 安装依赖

      - name: Start the project
        run: npm start  # 启动项目
